/**
 * Shows a list of pokemon that has a certain type that is boosted by the current
 * weather. The user can pick a certain pokemon and view their pokedex entry in the
 * pokedex window. User can also access their inventory and list what pokemon that they 
 * have from Pokemon go and their stats.
 */

package forms;

public class PokemonWindow extends javax.swing.JFrame {
    private MainWindow mainwindow;
    private WeatherWindow weatherwindow;
//    private PokemonWindow pokemonwindow;
    private PokedexWindow pokedexwindow;
    private PokemonInventoryWindow pokemoninventorywindow;
    /**
     * Creates new form PokemonWindow
     */
    public PokemonWindow() {
        initComponents();
//        weatherwindow = new WeatherWindow();
        pokedexwindow = new PokedexWindow();
        pokemoninventorywindow = new PokemonInventoryWindow();
        pokedexwindow.setPokemonWindow(this);
        pokemoninventorywindow.setPokemonWindow(this);    
    }
    
    public void setWeatherWin(WeatherWindow myCreator){
        weatherwindow = myCreator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PokemonList = new javax.swing.JList<>();
        weatherBtn = new javax.swing.JButton();
        pokedexBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PokemonList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(PokemonList);

        weatherBtn.setText("Weather");

        pokedexBtn.setText("Pokedex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(weatherBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokedexBtn)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weatherBtn)
                    .addComponent(pokedexBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        PokemonWindow pokemonwindow = new PokemonWindow();
        pokemonwindow.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PokemonList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pokedexBtn;
    private javax.swing.JButton weatherBtn;
    // End of variables declaration//GEN-END:variables
}
